# Task IDs:
#uint32 NO_TASK = 0
#uint32 PERFORM_WAYPOINTS = 1
#uint32 WAIT_FOR_USER_ACK = 2
#uint32 CHARGE_BATTERY = 3
#uint32 DO_NOTHING = 4
#uint32 TELEOPERATION = 5

runTasksPeriodically: true

clients:
    - r1:
#        - task:
#            taskId: 1
#            goalId: 62
#        - task:
#            taskId: 1
#            goalId: 25

        - task:
            taskId: 1
            goalId: 22

        - task:
            taskId: 1
            goalId: 53
        - task:
            taskId: 1
            goalId: 33
    - r2:
        - task:
            taskId: 1
            goalId: 62
        - task:
            taskId: 1
            goalId: 66

        - task:
            taskId: 4
            timeout: 5

